#普通的key-value
#对空格的要求十分严格
#name: zhaoyaopeng
##对象
#student:
#  name: zyp
#  age: 5
#
#
#
#
##行内写法
#student: {name: zhao,age: 3}
#
##数组
#pets:
#  - cat
#  - dog
#  - pig
#行内写法
#pets: [cat,dog,pig]
#server:
#  port:8082
person:
  name: zyp
  age: 3
  happy: false
  birth: 2022/11/02
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - music
    - girl
  dog:
    name: 旺财
    age: 3

